

>

> # Tasks
    1. Array Creation
        ◦ Create a 1D array of numbers from 10 to 50.
        ◦ Create a 3x3 array of random numbers between 0 and 1.
    2. Array Attributes
        ◦ Find the shape, size, and data type of the array you created in the previous task.
    3. Basic Operations
        ◦ Add 5 to every element of a 1D array.
        ◦ Multiply two 2D arrays element-wise.
    4. Indexing and Slicing
        ◦ Create a 5x5 array of integers from 1 to 25. Extract:
            ▪ The first row.
            ▪ The last column.
            ▪ A subarray of the first three rows and first two columns.
    5. Aggregation
        ◦ Create a 10-element array of random integers between 1 and 100. Find:
            ▪ The maximum value.
            ▪ The minimum value.
            ▪ The mean and standard deviation.
    6. Reshaping
        ◦ Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
    7. Broadcasting
        ◦ Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
    8. Filtering
        ◦ Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
    9. Matrix Multiplication
        ◦ Create two 2x2 matrices and perform matrix multiplication.
    10. Advanced Indexing
        ◦ Given a 4x4 array, use fancy indexing to extract the diagonal elements.





In [1]:
# 1. Array Creation
#     ◦ Create a 1D array of numbers from 10 to 50.
#     ◦ Create a 3x3 array of random numbers between 0 and 1.

import numpy as np
array_1d = np.arange(10, 51)
array_2d_random = np.random.rand(3, 3)

print(array_1d)
print(array_2d_random)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.13674841 0.23319037 0.21382533]
 [0.98661015 0.56932744 0.46176327]
 [0.55736112 0.76963824 0.99615133]]


In [2]:
# 2. Array Attributes
#     ◦ Find the shape, size, and data type of the array you created in the previous task.

print(array_1d.shape)
print(array_1d.size)
print(array_1d.dtype)


(41,)
41
int64


In [3]:
# 3. Basic Operations
#     ◦ Add 5 to every element of a 1D array.
#     ◦ Multiply two 2D arrays element-wise.

array_1d_plus_5 = array_1d + 5
array_2d_1 = np.random.rand(2, 2)
array_2d_2 = np.random.rand(2, 2)
elementwise_multiply = array_2d_1 * array_2d_2

print(array_1d_plus_5)
print(elementwise_multiply)


[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[9.30600749e-05 9.24042039e-02]
 [2.75886957e-01 4.89960739e-01]]


In [4]:
# 4. Indexing and Slicing
#     ◦ Create a 5x5 array of integers from 1 to 25. Extract:
#         ▪ The first row.
#         ▪ The last column.
#         ▪ A subarray of the first three rows and first two columns.

array_5x5 = np.arange(1, 26).reshape(5, 5)

first_row = array_5x5[0, :]
last_column = array_5x5[:, -1]
subarray = array_5x5[:3, :2]

print(first_row)
print(last_column)
print(subarray)


[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [5]:
# 5. Aggregation
#     ◦ Create a 10-element array of random integers between 1 and 100. Find:
#         ▪ The maximum value.
#         ▪ The minimum value.
#         ▪ The mean and standard deviation.

random_integers = np.random.randint(1, 101, 10)

print(np.max(random_integers))
print(np.min(random_integers))
print(np.mean(random_integers))
print(np.std(random_integers))


91
3
41.9
23.496595498071628


In [6]:
# 6. Reshaping
#     ◦ Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.

array_1d_reshaped = np.arange(1, 13).reshape(3, 4)
print(array_1d_reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# 7. Broadcasting
#     ◦ Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.

matrix_ones = np.ones((3, 3))
array_1d = np.array([1, 2, 3])
broadcasted_addition = matrix_ones + array_1d

print(broadcasted_addition)


[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [8]:
# 8. Filtering
#     ◦ Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.

random_integers_1d = np.random.randint(1, 51, 10)
filtered_elements = random_integers_1d[random_integers_1d % 5 == 0]

print(filtered_elements)


[40 45 20 45]


In [9]:
# 9. Matrix Multiplication
#     ◦ Create two 2x2 matrices and perform matrix multiplication.

matrix_1 = np.random.rand(2, 2)
matrix_2 = np.random.rand(2, 2)
matrix_multiplication = np.dot(matrix_1, matrix_2)

print(matrix_multiplication)


[[0.54270999 0.59027161]
 [0.25291694 0.29822828]]


In [10]:
# 10. Advanced Indexing
#     ◦ Given a 4x4 array, use fancy indexing to extract the diagonal elements.

array_4x4 = np.random.rand(4, 4)
diagonal_elements = np.diagonal(array_4x4)

print(diagonal_elements)


[0.20478146 0.69654639 0.6236361  0.00607745]
